[package]
name = "ps"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
rayon = "1.11"
owo-colors = "4.0"
thiserror = "2.0.17"
once_cell = "1.19"

[dev-dependencies]
assert_cmd = "2.0"